.

diff --git a/tmp/wgc b/tmp/wgc
--- a/tmp/wgc
+++ b/tmp/wgc
@@ -51,10 +51,11 @@ set_markers() {
     X=$'\e[01;31m'$X$'\e[m' # red CROSS MARK
     W=$'\e[01;31m'$W$'\e[m' # red BALLOT X
   fi
+  declare -gr W X Y
 }
 
 set_cfgdir() {
-  declare -g -r CFGDIR=${WGC_CFGDIR:-/etc/wireguard}
+  declare -gr CFGDIR=${WGC_CFGDIR:-/etc/wireguard}
   # Validate directory
   [[ ! -d "$CFGDIR" ]] && \
     error "Configuration directory not found: $CFGDIR
@@ -76,18 +77,29 @@ check_dependencies() {
   fi
 }
 
-check_resolvconf_capability() {
-  if [[ ! $(resolvconf -h 2>/dev/null) =~ -x[[:blank:]][[:blank:].A-Za-z]*[[:blank:]]exclusive ]]; then
-    local tailmsg=
-    [[ -d /run/systemd/resolve ]] && tailmsg+="
-      This system has systemd-resolved.
-      To bypass debian package conflict with openresolv use 'wgc openresolv' instead of 'apt-get install openresolv'."
+has_openresolv() {
+  [[ $(resolvconf -h 2>/dev/null) =~ -x[[:blank:]][[:blank:].A-Za-z]*[[:blank:]]exclusive ]]
+}
+
+check_openresolv() {
+  if ! has_openresolv; then
+    local tailmsg='Please run: apt-get install openresolv'
+    [[ -d /run/systemd/resolve ]] && tailmsg="This system has systemd-resolved.
+      To bypass debian package conflict with openresolv run 'wgc openresolv' instead of 'apt-get install openresolv'.
+      To remove openresolv installed by wgc run 'wgc remopenresolv'."
     error "Your version of 'resolvconf' does not support exclusive mode (-x).
-           Please install 'openresolv'.$tailmsg" fatal blameparent
+           $tailmsg" fatal blameparent
   fi
 }
 
 install_forced_openresolv() {
+  has_openresolv && error "Openresolv is already installed ('resolvconf' supports exclusive mode -x)." fatal blameparent
+
+  if [[ ! -d /run/systemd/resolve ]]; then
+    error "Systemd-resolved NOT detected. Standard installation is possible.
+           Please install 'openresolv' using: sudo apt-get install openresolv" fatal blameparent
+  fi
+
   echo "Forcing openresolv installation..."
 
   if ! dpkg-divert --list | grep -q "/usr/sbin/resolvconf"; then
@@ -103,7 +115,7 @@ install_forced_openresolv() {
     echo "Download via APT successful."
   else
     echo "APT download failed (package likely missing)."
-    local BASE_URL="http://ftp.debian.org/debian/pool/main/o/openresolv/"
+    local BASE_URL="https://ftp.debian.org/debian/pool/main/o/openresolv/"
     echo "Attempting direct Debian Pool download from $BASE_URL ..."
 
     # Find latest .deb file: openresolv_X.X.X-X_all.deb
@@ -123,15 +135,16 @@ install_forced_openresolv() {
 
   local DEB_FILE=$(find . -name "openresolv*.deb" | head -n 1)
 
-  echo "Extracting $DEB_FILE..."
-  dpkg-deb -x "$DEB_FILE" extracted_pkg
-
   echo "Creating file manifest..."
   mkdir -p /etc/wwggcc
-  find extracted_pkg -type f | sed 's|^extracted_pkg||' > /etc/wwggcc/openresolv.files
 
-  echo "Copying files to system..."
-  cp -R extracted_pkg/* /
+  dpkg-deb --fsys-tarfile "$DEB_FILE" | tar -tf - | grep -v '/$' | sed 's|^./|/|' > /etc/wwggcc/openresolv.files
+
+  echo "Extracting directly to system..."
+  dpkg-deb --fsys-tarfile "$DEB_FILE" | tar --keep-directory-symlink -xC /
+
+  cd ..
+  rm -rf "$TEMP_DIR"
 
   echo "Detecting DNS backend..."
   if [[ -d /run/systemd/resolve ]]; then
@@ -150,11 +163,8 @@ install_forced_openresolv() {
     echo "Systemd-resolved NOT detected. Leaving standard configuration."
   fi
 
-  cd ..
-  rm -rf "$TEMP_DIR"
-
   echo "Regenerating resolvconf..."
-  resolvconf -u
+  /sbin/resolvconf -u
 
   if command -v mandb >/dev/null; then
     echo "Updating the manual page index caches..."
@@ -166,9 +176,17 @@ install_forced_openresolv() {
 }
 
 remove_openresolv() {
-  local MANIFEST="/etc/wwggcc/openresolv.files"
+  local MANIFEST=/etc/wwggcc/openresolv.files
 
   echo "Removing openresolv..."
+
+  if ! dpkg-divert --list | grep -q "/usr/sbin/resolvconf"; then
+    error "No package diversion found. Assuming standard APT management.
+           To uninstall 'openresolv', please use: sudo apt remove openresolv" fatal blameparent
+  fi
+
+  echo "Removing diversion of resolvconf binary..."
+  dpkg-divert --rename --remove /usr/sbin/resolvconf
 
   if [[ -f "$MANIFEST" ]]; then
     echo "Deleting installed files..."
@@ -183,21 +201,20 @@ remove_openresolv() {
 
   rmdir /usr/lib/resolvconf 2>/dev/null || true
 
-  # 3. Gestione Diversion (Il cuore del ripristino)
-  echo "Restoring systemd-resolved wrapper..."
-
-  if [[ -f /usr/sbin/resolvconf ]] && [[ ! -L /usr/sbin/resolvconf ]]; then
-     rm /usr/sbin/resolvconf
+  echo "Restoring system DNS symlink..."
+  if [[ -f /etc/resolv.conf ]] && [[ ! -L /etc/resolv.conf ]]; then
+    rm -f /etc/resolv.conf
+    ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
   fi
 
-  if dpkg-divert --list | grep -q "/usr/sbin/resolvconf"; then
-    dpkg-divert --rename --remove /usr/sbin/resolvconf
-  else
-    echo "Diversion not found, trying explicit reinstall of systemd-resolved..."
-    apt-get install --reinstall -y systemd-resolved
-  fi
+  echo "Restoring systemd resolvconf symlink..."
+  rm -f /usr/sbin/resolvconf
+  ln -sf /usr/bin/resolvectl /usr/sbin/resolvconf
 
-  command -v mandb >/dev/null && mandb -pq
+  if command -v mandb >/dev/null; then
+    echo "Updating the manual page index caches..."
+    mandb -pq
+  fi
 
   echo "Done. System returned to APT management."
 }
@@ -206,14 +223,15 @@ list_config_files() {
   local f= g=
   set_cfgdir
   echo -e "Looking in $CFGDIR\n"
-  printf "%-12s %-18s %-26s %s\n" "Name" "Address" "Endpoint" "AllowedIPs"
-  printf "%-12s %-18s %-26s %s\n" "----" "-------" "--------" "----------"
+  printf "%-12s %-18s %-29s %s\n" "Name" "Address" "Endpoint" "AllowedIPs"
+  printf "%-12s %-18s %-29s %s\n" "----" "-------" "--------" "----------"
   for f in $CFGDIR/*.conf; do
     [[ "$f" == "$CFGDIR/*.conf" ]] && return 0
     g=${f##*/}; g=${g%.*}
     [[ $g =~ wg[0-9]+ ]] && continue # exclude wg0, wg1, wg2 ...
     parse_config_file "$g" relax || continue
-    printf "%-12s %-18s %-26s %s\n" "$g" "$Address" "$Endpoint" "$AllowedIPs"
+    (( ${#Endpoint} > 29 )) && Endpoint="${Endpoint:0:27}.."
+    printf "%-12s %-18s %-29s %s\n" "$g" "$Address" "$Endpoint" "$AllowedIPs"
   done
 }
 
@@ -479,15 +497,30 @@ exec_in_namespace() {
   [[ $IN_NAMESPACE ]] || error "VPN $DEV is not in its own namespace. Just use plain command: $@" fatal
 
   if [[ $(</proc/$PPID/comm) == sudo ]]; then
-    # wgc auto-elevated or executed with sudo: scraping of original environment limited to allowed vars
-    local orig_pid var_eq_val var REAL_IP REAL_SETPRIV keepfile=/etc/wwggcc/keepenv line
+    # wgc auto-elevated or executed with sudo.
+    # sudo inherits and sanitizes the original environment (depending on the active security policy) before executing wgc.
+    # Therefore, we enforce a special policy here: the final command will run with an environment consisting solely of
+    # variables from the original environment that are explicitly allowed in /etc/wwggcc/keepenv.
+    # To achieve this, we must identify the sudo PID, read its environment from /proc/$sudo_pid/environ, then clear and
+    # repopulate the environment via 'env -i'.
+    #
+    local sudo_pid var_eq_val var keepfile=/etc/wwggcc/keepenv line
+
+    command -v setpriv >/dev/null || error "Missing command 'setpriv'" fatal
+    [[ $SUDO_UID ]] || error "Unable to determine invoking user (SUDO_UID missing)" fatal
 
     if [[ ! -f $keepfile ]]; then
-      mkdir -p /etc/wwggcc
-      printf "%s\n" PATH TERM COLORTERM DISPLAY XAUTHORITY WAYLAND_DISPLAY LANG LANGUAGE LC_ALL USER HOME EDITOR \
-        VISUAL PAGER LESS SHELL SSH_AUTH_SOCK > "$keepfile"
+      # Create a basic /etc/wwggcc/keepenv
+      mkdir -p "${keepfile%/*}"
+      printf "%s\n" 'PATH # probably needed' 'HOME # also needed' \
+        '# you can put many names on the same line' 'SHELL LANG LC_ALL TERM COLORTERM LANGUAGE' \
+        'USER EDITOR VISUAL PAGER LESS' 'XAUTHORITY DISPLAY WAYLAND_DISPLAY # required for GUI apps' \
+        '# standard XDG base directories' 'XDG_RUNTIME_DIR XDG_CONFIG_HOME XDG_DATA_HOME XDG_CACHE_HOME' \
+        'DBUS_SESSION_BUS_ADDRESS # desktop notifications/keyring' 'GPG_TTY # enables gpg key signing' \
+        'SSH_AUTH_SOCK # enables ssh-agent forwarding' > "$keepfile"
     fi
 
+    # Build the list (map) of allowed variable names
     local -A ALLOWLIST
     while read -r line || [[ -n $line ]]; do
       line=${line%%#*} # Strip comments
@@ -496,17 +529,19 @@ exec_in_namespace() {
       done
     done < "$keepfile"
 
-    # save genuine command paths before root's PATH is overwritten
-    REAL_IP=$(command -v ip) || error "Missing command 'ip'" fatal
-    REAL_SETPRIV=$(command -v setpriv) || error "Missing command 'setpriv'" fatal
-
-    read -r _ _ _ orig_pid _ < /proc/$PPID/stat
+    # Build the environment for the final command
+    local -a FINAL_ENV
+    read -r _ _ _ sudo_pid _ < /proc/$PPID/stat # get sudo pid
     while IFS= read -r -d '' var_eq_val; do
       var=${var_eq_val%%=*}
-      [[ ${ALLOWLIST[$var]} ]] && export "$var_eq_val"
-    done < /proc/$orig_pid/environ
+      [[ $var == @(_WGC_*|SUDO_*) ]] && continue
+      [[ -v ALLOWLIST[$var] ]] && FINAL_ENV+=("$var_eq_val")
+    done < /proc/$sudo_pid/environ
 
-    exec "$REAL_IP" netns exec $NAMESPACE "$REAL_SETPRIV" --reuid $SUDO_UID --regid $SUDO_GID --init-groups "$@"
+    # Final command
+    exec ip netns exec $NAMESPACE \
+         setpriv --reuid $SUDO_UID --regid $SUDO_GID --init-groups \
+         env -i "${FINAL_ENV[@]}" "$@"
   else
     # wgc executed by root
     exec ip netns exec $NAMESPACE "$@"
@@ -678,7 +713,7 @@ start_vpn() {
     NSCMD="ip netns exec $NAMESPACE"
   else
     NSCMD=
-    check_resolvconf_capability
+    check_openresolv
   fi
 
   push_cleanup clean_vpn # Clean slate - removes namespace, interface, DNS config
@@ -894,8 +929,8 @@ error() {
     exit 1
   fi
 
-  [[ -n "$original_trap" ]] && eval "$original_trap"
-  [[ "$original_opts" == *e* ]] && set -e
+  [[ $original_trap ]] && eval "$original_trap"
+  [[ $original_opts == *e* ]] && set -e
   return 0 # allow to use error() as soft error handler without adding ||true to avoid trap ERR and recursion
 }
 
