.

diff --git a/.tmp/wgc b/.tmp/wgc
--- a/.tmp/wgc
+++ b/.tmp/wgc
@@ -340,7 +340,7 @@ start_vpn() {
 
   # get parameters and forwarding bridges from config file named $VPN
   local -A PARAMETER_VAL PARAMETER_LINE
-  parse_config_file $VPN ${p_nup:+bridges}
+  parse_config_file $VPN $([[ $CMD == nup ]] && echo bridges)
 
   [[ ${PARAMETER_VAL[MTU]:-} ]] && compute_mtu
 
@@ -352,7 +352,7 @@ start_vpn() {
   # Override AllowedIPs for Full Tunnel (fup), Bind-Only (bup/bupd) and Namespace (nup) modes.
   # Instructs WireGuard to allow all traffic in and out of the tunnel.
   if [[ $CMD == @(fup|bup?(d)|nup) ]]; then
-    AllowedIPs="0.0.0.0/0" # add " ::/0" if IPv6 supported
+    PARAMETER_VAL[[Interface]:AllowedIPs]="0.0.0.0/0" # add " ::/0" if IPv6 supported
   fi
 
   # Configure WireGuard
@@ -395,9 +395,11 @@ configure_vpn_plain() {
   # Configure interface $DEV
   ip link set $DEV mtu ${PARAMETER_VAL[MTU]} || error "Failed to configure MTU '${PARAMETER_VAL[MTU]}' for interface '$DEV'" fatal
 
-  for
-  ip addr add "$Address" dev $DEV || error "Failed to configure address '$Address' for interface '$DEV'" fatal
-  ip link set $DEV up || error "Failed to bring up interface '$DEV' with address '$Address'" fatal
+  local addr
+  IFS=, for addr in ${PARAMETER_VAL[[Interface]:Address]}; do
+    ip addr add "$addr" dev $DEV || error "Failed to configure address '$addr' for interface '$DEV'" fatal
+  done
+  ip link set $DEV up || error "Failed to bring up interface '$DEV'" fatal
 
   # Always add default route valid only for source $Address (source policy routing)
   set_source_routing
@@ -440,7 +442,7 @@ set_override_default_route() {
 }
 
 set_endpoint_host_route() {
-  local ep=${Endpoint%%:*} route
+  local ep=${PARAMETER_VAL[[Peer]:Endpoint]%%:*} route
   local -a route_args
   is_valid_ipv4 "$ep" || read -r ep _ < <(getent ahostsv4 "$ep") || \
     error "Cannot resolve Endpoint name '$ep'" fatal blameparent
@@ -960,9 +962,9 @@ parse_config_file() {
   [[ -f "$config_file" ]] || { error "Config file not found: $config_file" $fatal blameparent; return 1; }
   [[ -r "$config_file" ]] || { error "Can't read file: $config_file" $fatal blameparent; return 1; }
 
-  local line= n=0 s=0 section= key= value= ISSUES=
+  local line n=0 section= key value
   local -A SEEN_SECTIONS=()
-  local -a UNKNOWN_PARAMETERS=()
+  local -a ISSUES=()
   WGC_BRIDGES=()
   while read -r line || [[ $line ]]; do # also read last line if \n is missing
       ((++n))
@@ -971,16 +973,15 @@ parse_config_file() {
       if [[ $line =~ ^[[:space:]]*(\[[A-Za-z0-9_-]+\])[[:space:]]*$ ]]; then
         # This line is a section.
         section=${BASH_REMATCH[1]} # Track section
-        s=$n # remember section line number
         if ! process_config_line checksection; then
-          ISSUES+=$'\n'"Unknown section '$section' at line $s"
+          add_issue $n "Unknown section $section"
           section=BADSECTION
           continue
         fi
         # Section is valid.
         # If section was seen before, mark it as bad...
         if [[ -v SEEN_SECTIONS[$section] ]]; then
-          ISSUES+=$'\n'"Ignored duplicate section $section at line $s"
+          add_issue $n "Ignored duplicate section $section"
           section=BADSECTION
           continue
         fi
@@ -992,7 +993,7 @@ parse_config_file() {
       # Skip lines in bad sections (even before all sections)
       case "$section" in
         BADSECTION) continue ;;
-        "") ISSUES+=$'\n'"Ignored data before sections at line $n"
+        "") add_issue $n "Ignored data before sections"
             section=BADSECTION; continue ;;
       esac
       # Parse key=value with flexible spacing
@@ -1000,20 +1001,29 @@ parse_config_file() {
         key=${BASH_REMATCH[1]}   # trimmed, alphanumeric
         value=${BASH_REMATCH[2]} # trimmed, no leading or trailing commas
       else # Not a key=value line
-        ISSUES+=$'\n'"Malformed line $n: ${line:0:50}$( ((${#line} > 50)) && echo ... || true )"
+        add_issue $n "Malformed line in section $section"
         continue
       fi
       # Get values according to section/key
       process_config_line
   done < "$config_file"
   if [[ ! $p_relax ]]; then
-    if validate_parameters; then
-      [[ $ISSUES ]] && warn "Issues in $config_file:$ISSUES"
+    local issues
+    if issues=$(validate_parameters); then
+      [[ $issues ]] && warn "Issues in $config_file:$issues"
     else
       fatal=fatal; [[ $p_report ]] && fatal=
-      error "Fatal issues in $config_file:$ISSUES" $fatal blameparent
+      error "Found fatal issues in $config_file:$issues" $fatal blameparent
     fi
   fi
+}
+
+add_issue() {
+  local n=$1 msg=$2.
+  local first_n=${n%%,*}
+  # Prefix the message with the line number (e.g., "10: Message")
+  # Join with newline if multiple issues exist for the same line index
+  ISSUES[first_n]+=$'\n'"$n: $msg"
 }
 
 process_config_line() {
@@ -1034,7 +1044,7 @@ process_config_line() {
     *) return 1 ;;
   esac
   [[ ${1:-} == checksection || $sect_ignore ]] && return 0
-  [[ $key_found ]] || { UNKNOWN_PARAMETERS+=( $section:$key:$n ); return 0; }
+  [[ $key_found ]] || { add_issue $n "Found unknown key '$key' in section $section"; return 0; }
   local k="$section:$key" line=$n
   [[ -v PARAMETER_VAL[$k] ]] && { value=,$value; line=,$line; }
   PARAMETER_VAL[$k]=${PARAMETER_VAL[$k]:-}$value
@@ -1043,7 +1053,7 @@ process_config_line() {
 }
 
 validate_parameters() {
-  local p v n k section key IFS=:
+  local p v n k f d b section key IFS=:
   local -A USED_BRPORTS=()
   local -A REQUIRED_PARAMETERS=( [[Interface]:Address]=1 [[Interface]:PrivateKey]=1 \
                                  [[Peer]:PublicKey]=1 [[Peer]:Endpoint]=1 [[Peer]:AllowedIPs]=1 )
@@ -1055,31 +1065,27 @@ validate_parameters() {
         case "$key" in
           Address)
             unset REQUIRED_PARAMETERS[$p]
-            collect_all_ipv4_cidr "$v" PARAMETER_VAL[$p] k && continue
-            ((k>0)) && ISSUES+=$'\n'"FATAL: Found $k bad tokens in $key at line $n."
-            ISSUES+=$'\n'"FATAL: Could not find any CIDR IPv4 in $key at line $n."
+            collect_all_ipv4_cidr "$v" PARAMETER_VAL[$p]
             ;;
           DNS)
-            collect_all_ipv4 "$v" PARAMETER_VAL[$p] k && continue
-            ((k>0)) && ISSUES+=$'\n'"FATAL: Found $k bad tokens in $key at line $n."
-            ISSUES+=$'\n'"FATAL: Could not find any IPv4 in $key at line $n."
+            collect_all_ipv4 "$v" PARAMETER_VAL[$p]
             ;;
           MTU)
             [[ $v =~ ^[0-9]+$ ]] && ((v >= 576 && v <= 65535)) && continue
-            ISSUES+=$'\n'"FATAL: Invalid $key value at line $n (must be 576-65535): $v"
+            add_issue $n "FATAL: Invalid $key value '$v' (must be 576-65535)"
             ;;
           PrivateKey)
             unset REQUIRED_PARAMETERS[$p]
             is_valid_key "$v" && continue
-            ISSUES+=$'\n'"FATAL: Invalid $key value at line $n."
+            add_issue $n "FATAL: Invalid $key value"
             ;;
           ListenPort)
             is_valid_port "$v" && continue
-            ISSUES+=$'\n'"FATAL: Invalid $key value at line $n (must be 1-65535): $v"
+            add_issue $n "FATAL: Invalid $key value '$v' (must be 1-65535)"
             ;;
           FwMark)
             is_valid_fwmark "$v" && continue
-            ISSUES+=$'\n'"FATAL: Invalid $key value at line $n (must be 0-4294967295 0x0-0xFFFFFFFF): $v"
+            add_issue $n "FATAL: Invalid $key value '$v' (must be 0-4294967295 0x0-0xFFFFFFFF)"
             ;;
         esac
         ;;
@@ -1087,81 +1093,80 @@ validate_parameters() {
         case "$key" in
           AllowedIPs)
             unset REQUIRED_PARAMETERS[$p]
-            collect_all_ipv4_cidr "$v" PARAMETER_VAL[$p] k && continue
-            ((k>0)) && ISSUES+=$'\n'"FATAL: Found $k bad tokens in $key at line $n."
-            ISSUES+=$'\n'"FATAL: Could not find any CIDR IPv4 in $key at line $n."
+            collect_all_ipv4_cidr "$v" PARAMETER_VAL[$p]
             ;;
           Endpoint)
             unset REQUIRED_PARAMETERS[$p]
-            validate_resolve_endpoint "$v" k && continue
-            ISSUES+=$'\n'"FATAL: $k at line $n."
+            validate_resolve_endpoint
             ;;
           PersistentKeepalive)
             [[ $v =~ ^[0-9]+$ ]] && ((v >= 0 && v <= 65535)) && continue
-            ISSUES+=$'\n'"FATAL: Invalid $key value at line $n (must be 0-65535): $v"
+            add_issue $n "FATAL: Invalid $key value, must be 0-65535" $section
             ;;
           PresharedKey)
             is_valid_key "$v" && continue
-            ISSUES+=$'\n'"FATAL: Invalid $key value at line $n."
+            add_issue $n "FATAL: Invalid $key value '$v'" $section
             ;;
           PublicKey)
             unset REQUIRED_PARAMETERS[$p]
             is_valid_key "$v" && continue
-            ISSUES+=$'\n'"FATAL: Invalid $key value at line $n."
+            add_issue $n "FATAL: Invalid $key value '$v'" $section
             ;;
         esac
         ;;
       "[WGC-Bridges]")
         local ext_port= int_port=
-        ISSUES+=$(validate_bridge) || continue
+        validate_bridge || continue
         USED_BRPORTS[$ext_port]=$key
         PARAMETER_VAL[$p]=$ext_port:$int_port
         ;;
     esac
   done
   local IFS=,
-  (( ${#REQUIRED_PARAMETERS[@]} > 0 )) && ISSUES+=$'\n'"FATAL: Missing required keys (section:key): ${!REQUIRED_PARAMETERS[*]}"
-  (( ${#UNKNOWN_PARAMETERS[@]} > 0 )) && ISSUES+=$'\n'"Found unknown keys (section:key:line): ${UNKNOWN_PARAMETERS[*]}"
-  [[ $ISSUES == *FATAL:* ]] && return 1
+  (( ${#REQUIRED_PARAMETERS[@]} > 0 )) && add_issue 0 "FATAL: Missing required keys (section:key): ${!REQUIRED_PARAMETERS[*]}"
+  local IFS='' issues="${ISSUES[*]}"
+  printf %s "$issues"
+  [[ $issues == *FATAL:* ]] && return 1
   return 0
 }
 
 validate_bridge() {
   if [[ $v == *,* ]]; then
-    printf '\n%s' "FATAL: Duplicated bridge '$key' at lines $n."
+    add_issue $n "FATAL: Duplicated bridge '$key'" $section
     return 1
   fi
   if [[ ! $v =~ ^([0-9]+)[[:space:]]*:[[:space:]]*([0-9]+)$ ]]; then
-    printf '\n%s' "FATAL: Bridge '$key' at line $n has invalid format (must be <number>:<number>): $v"
+    add_issue $n "FATAL: Bridge '$key' has invalid format '$v', must be <number>:<number>" $section
     return 1
   fi
   ext_port="${BASH_REMATCH[1]}"; int_port="${BASH_REMATCH[2]}"
-  if ! is_valid_port $ext_port || ! is_valid_port $int_port; then
-    printf '\n%s' "FATAL: Bridge '$key' at line $n has invalid port (must be 1-65535): $value"
+  if ! is_valid_port $ext_port; then
+    add_issue $n "FATAL: Bridge '$key' has invalid port '$ext_port', must be 1-65535" $section
+    return 1
+  fi
+  if ! is_valid_port $int_port; then
+    add_issue $n "FATAL: Bridge '$key' has invalid port '$int_port', must be 1-65535" $section
     return 1
   fi
   if [[ -v USED_BRPORTS[$ext_port] ]]; then
-    printf '\n%s%s' "FATAL: Bridges '$key' at line $n and '${USED_BRPORTS[$ext_port]}' at line " \
-      "${PARAMETER_LINE[$section:${USED_BRPORTS[$ext_port]}]} have conflicting external port $ext_port."
+    local issue="FATAL: Bridge '$key' has external port '$ext_port' conflicting with bridge "
+    issue+="'${USED_BRPORTS[$ext_port]}' at line ${PARAMETER_LINE[$section:${USED_BRPORTS[$ext_port]}]}"
+    add_issue $n "$issue" $section
     return 1
   fi
   return 0
 }
 
 validate_resolve_endpoint() {
-  local -n _msg=$2
-  if [[ ! $1 =~ ^([-A-Za-z0-9.]+):([0-9]{1,5})$ ]]; then
-    _msg="Invalid Endpoint value '$1'"
-    return 1
+  if [[ ! $v =~ ^([-A-Za-z0-9.]+):([0-9]{1,5})$ ]]; then
+    add_issue $n "FATAL: Invalid $key value '$v'"
   fi
   local _host=${BASH_REMATCH[1]}; local _port=${BASH_REMATCH[2]}
   if ! is_valid_port "$_port"; then
-    _msg="Invalid port '$_port' in Endpoint"
-    return 1
+    add_issue $n "FATAL: Invalid $key port '$_port'"
   fi
   is_valid_ipv4 "$_host" || getent ahostsv4 "$_host" &>&- || {
-    _msg="Could not resolve Endpoint host '$_host'"
-    return 1
+    add_issue $n "FATAL: Could not resolve $key host '$_host'"
   }
   return 0
 }
@@ -1171,41 +1176,40 @@ is_valid_port() {
   [[ $p =~ ^(0|[1-9][0-9]*)$ ]] && ((p >= 1 && p <= 65535))
 }
 
-# local -a ARRAY
-# extract_all_val ' one, two  three , four , ' ARRAY
-# declare -p ARRAY # declare -a ARRAY=([0]="one" [1]="two" [2]="three" [3]="four")
-collect_all_val() {
-  local -n _a=$2
-  local IFS=$' \t\n'
-  _a=( ${1//,/ } )
-}
-
 collect_all_ipv4() {
-  local _in=$1
-  local -n _a=$2 _c=$3
-  _a=; _c=0
-  local _ip
+  local _in=$1 _f=0 _d=0 _b=0
+  local -n _a=$2; _a=
+  local _ip IFS=' '
   for _ip in ${_in//,/ }; do
-    is_valid_ipv4 "$_ip" && _a+="$_ip," && continue
-    ((_c++))
+    if is_valid_ipv4 "$_ip"; then
+      [[ $_a, == *",$_ip,"* ]] && ((++_d)) && continue
+      _a+=",$_ip" && ((++_f)) && continue
+    fi
+    ((++_b))
   done
-  [[ $_a ]] || return 1
-  _a=${_a%,}
-  return ((_c>0))
+  _a=${_a#,}
+  ((f==0)) && add_issue $n "FATAL: Could not find any IPv4 in $key"
+  ((d>0))  && add_issue $n "FATAL: Found $d duplicate IPs in $key"
+  ((b>0))  && add_issue $n "FATAL: Found $b bad IPs in $key"
+  return 0
 }
 
 collect_all_ipv4_cidr() {
-  local _in=$1
-  local -n _a=$2 _c=$3
-  _a=; _c=0
-  [[ ${_in//,/ } ]] || return 1
-  local _ip
+  local _in=$1 _f=0 _d=0 _b=0
+  local -n _a=$2; _a=
+  local _ip _pure_ip IFS=' '
   for _ip in ${_in//,/ }; do
-    is_valid_ipv4_cidr "$_ip" && _a+="$_ip," && continue
-    ((_c++))
+    if is_valid_ipv4_cidr "$_ip"; then
+      _pure_ip=${_ip%/*}; [[ $_a, == *",$_pure_ip"@(/|,)* ]] && ((++_d)) && continue
+      _a+=",$_ip" && ((++_f)) && continue
+    fi
+    ((++_b))
   done
-  _a=${_a%,}
-  return ((_c>0))
+  _a=${_a#,}
+  ((f==0)) && add_issue $n "FATAL: Could not find any CIDR IPv4 in $key"
+  ((d>0))  && add_issue $n "FATAL: Found $d duplicate/overlapping CIDR IPs in $key"
+  ((b>0))  && add_issue $n "FATAL: Found $b bad CIDR IPs in $key"
+  return 0
 }
 
 is_valid_ipv4() {
