.

diff --git a/.tmp/wgc b/.tmp/wgc
--- a/.tmp/wgc
+++ b/.tmp/wgc
@@ -222,9 +222,9 @@ printf "\n%s\n\n" "$usage"
 acquire_lock() {
   local id=$1 msg=$2 lock_file="/var/run/wgc.${id}.lock" fd
 
-  exec {lock_fd}>"$lock_file" || error "Cannot create lock file: $lock_file" fatal blameparent
+  exec {fd}>"$lock_file" || error "Cannot create lock file: $lock_file" fatal blameparent
   if ! flock -n $fd; then
-    exec {lock_fd}>&-
+    exec {fd}>&-
     error "Another wgc instance is $msg. Try again in a moment." fatal blameparent
   fi
 
