.

diff --git a/.tmp/wgc b/.tmp/wgc
--- a/.tmp/wgc
+++ b/.tmp/wgc
@@ -17,60 +17,88 @@
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
 #
 
+# Guard against sourcing. Enable before release!
+# [[ "${BASH_SOURCE[0]}" == "$0" ]] || return 1
+
 doit() {
-  if [ -z "$BASH_VERSION" ]; then
-    echo "ERROR: This script requires Bash. Please run with 'wgc'." >&2
-    exit 1
+  local is_interactive=
+  [[ $- == *i* ]] && is_interactive=1
+  if [[ $is_interactive ]]; then
+    local interactive_state=$(shopt -p; set +o | grep -v history)
   fi
-  if ((BASH_VERSINFO[0] < 4)) || ((BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4)); then
-    echo "ERROR: Bash 4.4 or newer is required (found $BASH_VERSION)." >&2
-    exit 1
-  fi
+
+  safe_exit() {
+    set +vx # disable trace if enabled
+    local ret=${1:-0}
+    if [[ $is_interactive ]]; then
+      local h='+o history'
+      [[ -o history ]] && h='-o history'
+      set +o history # disable history to prevent history pollution by eval
+      set +o errexit # prevent possible eval crash
+      eval "$interactive_state"
+      set $h # restore history state
+      return $ret
+    fi
+    exit $ret
+  }
 
   # Set safe/trusted PATH
   export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
 
-  # Sanitized auto-elevation
-  [[ $UID == 0 ]] || exec sudo WGC_CFGDIR="$WGC_CFGDIR" BASH_ENV= ENV= CDPATH= IFS= "$0" "$@"
-  # unset fails when readonly
-  [[ ${BASH_ENV:-}${ENV:-}${CDPATH:-} ]] && \
-    exec /usr/bin/env -u BASH_ENV -u ENV -u CDPATH "$0" "$@"
+  if [ -z "$BASH_VERSION" ]; then
+    echo "ERROR: This script requires Bash. Please run with 'wgc'." >&2
+    safe_exit 1
+  fi
+  if ((BASH_VERSINFO[0] < 4)) || ((BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4)); then
+    echo "ERROR: Bash 4.4 or newer is required (found $BASH_VERSION)." >&2
+    safe_exit 1
+  fi
+
+  if [[ ! $is_interactive ]]; then
+    # Sanitized auto-elevation
+    [[ $UID == 0 ]] || exec sudo WGC_CFGDIR="$WGC_CFGDIR" BASH_ENV= ENV= CDPATH= IFS= "$0" "$@"
+    # unset fails when readonly, so use exec env -i
+    [[ ${BASH_ENV:-}${ENV:-}${CDPATH:-} ]] && \
+      exec /usr/bin/env -u BASH_ENV -u ENV -u CDPATH "$0" "$@"
+  fi
 
   set +vx
   [[ ${1:-} == trace ]] && { set -vx; shift; }
 
-  # Shell status baseline
+  # Shell state baseline
   set +abefhkmnptuBCEHPT
   shopt -u $(shopt | awk '/[[:space:]]on$/{print $1}')
   # What I want
   set +o posix       # Turn off Posix standard
   set -o hashall     # Remember the location of commands as they are looked up.
   set -o braceexpand # Perform brace expansion.
-  set -o errexit     # Exit immediately if a command exits with a non-zero status.
   set -o nounset     # Treat unset variables as an error.
   set -o pipefail    # Return value of a pipeline is the status of the last command to exit with a non-zero status.
-  set -o errtrace    # Trap ERR is inherited by functions.
   shopt -s extglob   # Enable extended glob patterns: x(y)
   shopt -s nullglob  # Patterns which match no files expand to a null string
   shopt -s checkwinsize extquote
   export LC_ALL=C LANG=C
   local IFS=$' \t\n'
-  trap 'error TRAP fatal' ERR
+  if [[ ! $is_interactive ]]; then
+    set -o errexit   # Exit immediately if a command exits with a non-zero status.
+    set -o errtrace  # Trap ERR is inherited by functions.
+    trap 'error TRAP fatal' ERR
+  fi
 
-  (( $# == 0 )) && { show_usage; exit; }
+  (( $# == 0 )) && { show_usage; safe_exit; }
 
   local -r CMD=${1:-} VPN=${2:-}
   local DEV=wgc_${VPN:-}
   local NAMESPACE=$DEV
 
-  local W X Y; set_markers; readonly W X Y
+  local W X Y HAS_COLORS; local -A COLORS; set_markers; readonly W X Y HAS_COLORS COLORS
   local CFGDIR; set_cfgdir; readonly CFGDIR
   local IS_CONNECTED HAS_NAMESPACE IN_NAMESPACE IS_WGC
   local Address PrivateKey PublicKey Endpoint AllowedIPs DNS MTU ListenPort PersistentKeepalive PresharedKey
   local -a WGC_BRIDGES
 
   case "$CMD" in
-    up|upd|n|nu|nup|d|do|dow|down|s|st|sta|stat|statu|status|e|ex|exe|exec)
+    up|upd|n|nu|nup|d|do|dow|down|s|st|sta|stat|state|e|ex|exe|exec)
       validate_vpn_name
       local ns=$(ip netns identify) || true
       [[ $ns ]] && error "Usage of wgc is not supported inside a network namespace ($ns)" fatal
@@ -99,8 +127,8 @@ doit() {
     d|do|dow|down)
       stop_vpn ${3:-} # can be "force"
       ;;
-    s|st|sta|stat|statu|status)
-      show_status bridges
+    s|st|sta|stat|state)
+      show_state bridges
       ;;
     e|ex|exe|exec)
       shift 2
@@ -124,15 +152,27 @@ doit() {
     remopenresolv)
       remove_openresolv
       ;;
+    null)
+      :
+      ;;
+    f)
+      "${@:2}"
+      ;;
+    ft)
+      PS4='+${LINENO}:${FUNCNAME[0]}: '
+      shopt -s promptvars
+      set -vx; "${@:2}"
+      ;;
     *)
       show_usage
       ;;
   esac
+  safe_exit
 }
 
 show_usage() {
   cat <<EOF
-Usage: wgc [options] [ [up|upd|nup|down|status] <vpn> | active | list | exec <vpn> <command> ]
+Usage: wgc [options] [ [up|upd|nup|down|state] <vpn> | active | list | exec <vpn> <command> ]
 
 <vpn> should match a config file name \$WGC_CFGDIR/<vpn>.conf
 Export WGC_CFGDIR to point to dir containing Wireguard *.conf files (default: /etc/wireguard).
@@ -142,7 +182,7 @@ Commands (can be shortened):
   upd    - Start VPN and add a "split route" (0.0.0.0/1 128.0.0.0/1)
   nup    - Start VPN in its own network namespace
   down   - Stop VPN
-  status - Show VPN status
+  state  - Show VPN state
   active - Show active VPNs
   list   - List config files
   conf   - Show config file <vpn>.conf
@@ -200,10 +240,67 @@ set_markers() {
   X=$'\u274C'
   W=$'\u2717'
   # Detect if terminal supports colors
+  HAS_COLORS=
   if [[ -t 1 ]] && (($(tput colors 2>/dev/null || echo 0) >= 8)); then
-    Y=$'\e[01;32m'$Y$'\e[m' # green CHECK MARK
-    X=$'\e[01;31m'$X$'\e[m' # red CROSS MARK
-    W=$'\e[01;31m'$W$'\e[m' # red BALLOT X
+    Y=$'\e[1;32m'$Y$'\e[m' # green CHECK MARK
+    X=$'\e[1;31m'$X$'\e[m' # red CROSS MARK
+    W=$'\e[1;31m'$W$'\e[m' # red BALLOT X
+    # colors
+     COLORS=( [A]=$'\e[1;30m' [R]=$'\e[1;31m' [G]=$'\e[1;32m' [Y]=$'\e[1;33m' )
+    COLORS+=( [B]=$'\e[1;34m' [M]=$'\e[1;35m' [C]=$'\e[1;36m' [W]=$'\e[1;37m' )
+    COLORS+=( [a]=$'\e[30m'   [r]=$'\e[31m'   [g]=$'\e[32m'   [y]=$'\e[33m'   )
+    COLORS+=( [b]=$'\e[34m'   [m]=$'\e[35m'   [c]=$'\e[36m'   [w]=$'\e[37m'   )
+    HAS_COLORS=1
+  fi
+}
+
+# prc - Print with color
+# Usage: prc [[C]FORMAT] [ARGS...]
+#
+# If C is one of ARGYBMCWargybmcw, color is applied as follows:
+#   Bright color: A:gray R:red G:green Y:yellow B:blue M:magenta C:cyan W:white
+#   Normal color: a      r     g       y        b      m         c      w
+# COLORS array maps letters to ANSI color codes.
+#
+# FORMAT: printf-style format string (default: %s)
+#
+# In short, it works exactly as printf, with three exceptions:
+# - If arg $1 begins with one of ARGYBMCWargybmcw, color is also applied
+#   and the remaining of $1 (FORMAT) is used as printf format.
+# - If FORMAT is empty, format %s is assumed.
+# - If there is only arg $1, it is printed literally (no orphaned format specifiers).
+#
+# Examples:
+#   prc "R%s\n" "Error: 234" # prints "Error: 234" in Bright Red + newline
+#   prc "RError: %d\n" 234   # equivalent, but somewhat obscure
+#   prc R%s "Error: 234"     # prints "Error: 234" in Bright Red
+#   prc R%s%d "Error: " 0xEA # equivalent
+#   prc R "Error: 234"       # equivalent
+#   prc "g%s" Success        # prints "Success" in Normal Green
+#   prc "gSuccess"           # prints "gSuccess" without ANSI color codes
+#   prc "%dSuccess"          # prints "%dSuccess"
+#   prc "%d files\n" 42      # prints "42 files" with no color + newline
+prc() {
+  local fmt=$1 color=
+
+  if (( $# > 1 )); then
+    # fmt is indeed a format
+    if [[ $fmt == [ARGYBMCWargybmcw]* ]]; then
+      # fmt first letter is a color, consume it
+      color=${fmt:0:1}
+      fmt=${fmt:1}; fmt=${fmt:-%s}
+    fi
+    shift # adjust "$@"
+  else
+    # fmt is a message -> set default format
+    fmt=%s
+  fi
+
+  if [[ $HAS_COLORS && $color ]]; then
+    #printf "%s$fmt\e[m" "${COLORS[$color]}" "$@"
+    printf "${COLORS[$color]}$fmt\e[m" "$@"
+  else
+    printf "$fmt" "$@"
   fi
 }
 
@@ -408,11 +505,12 @@ show_parsed_config_file() {
 
 show_config() {
   echo
-  printf "%-20s %s\n" Key Value
-  printf "%-20s %s\n" ---- -----
+  printf "%-20s%s\n" Key Value
+  printf "%-20s%s\n" ---- -----
   local pub
   for k in Address DNS MTU ListenPort PrivateKey PublicKey PresharedKey Endpoint AllowedIPs PersistentKeepalive; do
-    printf "%-20s %s" $k "${!k:-  (missing)}"
+    prc c%-20s $k
+    [[ ${!k} ]] && prc %s "${!k}" || prc "(missing)" Y
     if [[ $k ==  P*Key ]]; then
       if pub=$(wg pubkey <<<${!k} 2>/dev/null); then
         [[ $k == PrivateKey ]] && printf "\n└── %-16s %s" "PUBLIC" "$pub"
@@ -425,11 +523,11 @@ show_config() {
   if (( ${#WGC_BRIDGES[@]} > 0 )); then
     echo
     local bridge_data b_name b_ext b_int
-    printf "%-20s %s\n" "Forwarding Bridge" "ExtPort -> IntPort"
-    printf "%-20s %s\n"  -----------------   ------------------
+    printf "%-20s%s\n" "Forwarding Bridge" "ExtPort -> IntPort"
+    printf "%-20s%s\n"  -----------------   ------------------
     for bridge_data in "${WGC_BRIDGES[@]}"; do
       IFS=: read -r b_name b_ext b_int <<<"$bridge_data"
-      printf "%-20s %s\n" "$b_name" "$b_ext -> $b_int"
+      printf "%-20s%s\n" "$b_name" "$b_ext -> $b_int"
     done
   fi
   echo
@@ -779,7 +877,7 @@ _wgc_completion() {
   prev="${COMP_WORDS[COMP_CWORD-1]}"
 
   # Main commands
-  commands="conf parse up upd nup down status active list exec"
+  commands="conf parse up upd nup down state active list exec"
 
   # Complete the first arg with main commands
   if [[ $COMP_CWORD -eq 1 ]]; then
@@ -803,7 +901,7 @@ _wgc_completion() {
         done
         COMPREPLY=( $(compgen -W "$v" -- "$cur") )
         ;;
-      d|do|dow|down|s|st|sta|stat|statu|status)
+      d|do|dow|down|s|st|sta|stat|state)
         # Active VPNs in default namespace
         local -a ifaces
         ifaces=($(wg show interfaces 2>/dev/null)) || ifaces=(sudo $(wg show interfaces 2>/dev/null)) || return 1
@@ -815,7 +913,8 @@ _wgc_completion() {
         # Active VPNs (namespaces)
         local n
         while read -r n _; do
-          sudo /usr/sbin/ip netns exec "$n" wg show "$n" &>/dev/null && v+="${n#*wgc_} "
+          [[ $n == wgc_* ]] || continue
+          v+="${n#*wgc_} "
         done < <(/usr/sbin/ip netns list 2>/dev/null)
         COMPREPLY=( $(compgen -W "$v" -- "$cur") )
         ;;
@@ -823,7 +922,8 @@ _wgc_completion() {
         # Active VPNs (namespaces)
         local n v
         while read -r n _; do
-          sudo /usr/sbin/ip netns exec "$n" wg show "$n" &>/dev/null && v+="${n#*wgc_} "
+          [[ $n == wgc_* ]] || continue
+          v+="${n#*wgc_} "
         done < <(/usr/sbin/ip netns list 2>/dev/null)
         COMPREPLY=( $(compgen -W "$v" -- "$cur") )
         ;;
@@ -875,7 +975,6 @@ To avoid sudo password prompt:
   sudo visudo -f /etc/sudoers.d/wgc-completion
   Then add:
   %sudo ALL=(ALL) NOPASSWD: /usr/bin/find $CFGDIR -maxdepth 1 -name *.conf -type f
-  %sudo ALL=(ALL) NOPASSWD: /usr/sbin/ip netns exec * wg show *
 EOF
 }
 
@@ -1197,7 +1296,7 @@ start_vpn() {
 
   pop_cleanup clean_vpn
 
-  show_status
+  show_state
 
 }
 
@@ -1258,8 +1357,8 @@ show_bridges() {
 
           local int_unit="wgc.${VPN}.${name}.int.socket" # proxyd
           [[ $tool == socat ]] && int_unit="wgc.${VPN}.${name}.int.service"
-          local int_state="${u_active[$int_unit]:-missing}"
-          [[ $int_state != active ]] && status_str+=" / Int: $X $int_state"
+          local int_status="${u_active[$int_unit]:-missing}"
+          [[ $int_status != active ]] && status_str+=" / Int: $X $int_status"
 
           printf "  %-18s %-7s %-11s %-8s %s\n" "$name" "$p_ext" "-> $p_int" "$tool" "$status_str"
         fi
@@ -1270,7 +1369,7 @@ show_bridges() {
   fi
 }
 
-show_status() {
+show_state() {
   local p_bridges=
   eval "$(get_params "$@")"
 
